### ISSUE TITLE
APK and CLI in releases

### ISSUE THREAD

**Issue by chrissyhroberts** [chrissyhroberts/ODK_Fingerprints_Mantra#32]
Hi @seadowg. Great to see the latest release is now available. I wonder if you could please do a sub-release 0.41 to add the latest version of the APK and the CLI back to the assets. 

I’d love to do some testing of the APK and happy to provide some feedback from an end-user perspective if it would help. 

C.

**Comment by seadowg** [comment]
@chrissyhroberts I can add them to the v0.4 release as it looks like I still have a backup of the signing keys. Please let me know if you don't have them as if so I'll be the only person who's able to build updates.

Also just to point out: as I've noted in the release notes, the APK won't support BioMini scanners. I can chase up if it's possible to either include the SDK in the repo or if we can build and distribute an APK with it included.

**Comment by chrissyhroberts** [comment]
Hi @seadowg I’m not sure I ever had the signing keys for this one, so please keep them safe. 

Just to be clear on what scanners the new APK supports, will the new version 0.4 work on Mantra, BioMini or both?

**Comment by seadowg** [comment]
> Hi @seadowg I’m not sure I ever had the signing keys for this one, so please keep them safe.

Shoot me an email with somewhere safe I can send them, so I can make sure you've got a copy to!

> Just to be clear on what scanners the new APK supports, will the new version 0.4 work on Mantra, BioMini or both?

An APK built with the open source code would only support Mantra (below Android 12). I'm hoping we'll be able to include the BioMini SDK down the line though.

**Comment by seadowg** [comment]
(I've also just marked the release as a pre-release so it's clearer that not everything is supported yet).

**Comment by chrissyhroberts** [comment]
Thanks I’ll email you.

I’m still confused as to why the version 0.4 will be limited to Android 12 when my Android 14 device works with version 0.3. 
What am I missing?

**Comment by seadowg** [comment]
> I’m still confused as to why the version 0.4 will be limited to Android 12 when my Android 14 device works with version 0.3.
What am I missing?

Updates to the target/min API level for the app break the Mantra SDK sadly (as discussed [here](https://github.com/LSHTM-ORK/ODK_Biometrics/issues/13)). This is a pretty classic problem: we want the app to play with the latest Android, but doing so creates problems for older code (the Mantra SDK in this case) using an old API.
